-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.bank_tags_tag_id_seq...';END$$;
DROP SEQUENCE public.bank_tags_tag_id_seq;

SET check_function_bodies = true;
