-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.bank_tags...';END$$;
DROP TABLE public.bank_tags;

SET check_function_bodies = true;
