-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.account_roles...';END$$;
DROP TABLE public.account_roles;

SET check_function_bodies = true;
