-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.tab_test_1_id_seq...';END$$;
ALTER SEQUENCE public.tab_test_1_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.tab_test_1...';END$$;
DROP TABLE public.tab_test_1;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.tab_test_1_id_seq...';END$$;
DROP SEQUENCE public.tab_test_1_id_seq;

SET check_function_bodies = true;
