-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.users_id_seq...';END$$;
ALTER SEQUENCE public.users_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.users...';END$$;
DROP TABLE public.users;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.users_id_seq...';END$$;
DROP SEQUENCE public.users_id_seq;

SET check_function_bodies = true;
