-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.bill_new_id_seq...';END$$;
ALTER SEQUENCE public.bill_new_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.bill_new...';END$$;
DROP TABLE public.bill_new;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.bill_new_id_seq...';END$$;
DROP SEQUENCE public.bill_new_id_seq;

SET check_function_bodies = true;
