-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.autopilot...';END$$;
DROP TABLE public.autopilot;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.accounts_view...';END$$;
DROP VIEW public.accounts_view;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.insert_data(integer, integer)...';END$$;
DROP PROCEDURE public.insert_data(integer, integer);


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.account_roles.account_roles_user_id_fkey...';END$$;
ALTER TABLE public.account_roles DROP CONSTRAINT account_roles_user_id_fkey;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.account_roles.account_roles_role_id_fkey...';END$$;
ALTER TABLE public.account_roles DROP CONSTRAINT account_roles_role_id_fkey;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.account_roles...';END$$;
DROP TABLE public.account_roles;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.product_tags_tag_id_seq...';END$$;
ALTER SEQUENCE public.product_tags_tag_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.product_tags...';END$$;
DROP TABLE public.product_tags;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.product_tags_tag_id_seq...';END$$;
DROP SEQUENCE public.product_tags_tag_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.auto_test_tag_id_seq...';END$$;
ALTER SEQUENCE public.auto_test_tag_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.auto_test...';END$$;
DROP TABLE public.auto_test;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.auto_test_tag_id_seq...';END$$;
DROP SEQUENCE public.auto_test_tag_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.roles_role_name_key...';END$$;
DROP INDEX public.roles_role_name_key;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.roles_role_id_seq...';END$$;
ALTER SEQUENCE public.roles_role_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.roles...';END$$;
DROP TABLE public.roles;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.roles_role_id_seq...';END$$;
DROP SEQUENCE public.roles_role_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.accounts_username_key...';END$$;
DROP INDEX public.accounts_username_key;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.accounts_email_key...';END$$;
DROP INDEX public.accounts_email_key;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.accounts_user_id_seq...';END$$;
ALTER SEQUENCE public.accounts_user_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.accounts...';END$$;
DROP TABLE public.accounts;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.accounts_user_id_seq...';END$$;
DROP SEQUENCE public.accounts_user_id_seq;

SET check_function_bodies = true;
