-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.bank_tags...';END$$;
CREATE TABLE public.bank_tags (
    product_id integer NOT NULL,
    tag_id integer NOT NULL DEFAULT nextval('public.bank_tags_tag_id_seq'::regclass),
    production_date character varying(20),
    tag_peni character varying(20),
    item_number character varying(20)
);
ALTER TABLE public.bank_tags OWNER TO postgres;

SET check_function_bodies = true;
