-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.tab_test_1_id_seq...';END$$;
CREATE SEQUENCE public.tab_test_1_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.tab_test_1_id_seq OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.tab_test_1...';END$$;
CREATE TABLE public.tab_test_1 (
    id integer NOT NULL DEFAULT nextval('public.tab_test_1_id_seq'::regclass),
    name character varying(255) NOT NULL,
    description text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.tab_test_1 ADD CONSTRAINT tab_test_1_pkey PRIMARY KEY (id);
ALTER TABLE public.tab_test_1 OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.tab_test_1_id_seq...';END$$;
ALTER SEQUENCE public.tab_test_1_id_seq OWNED BY public.tab_test_1.id;

SET check_function_bodies = true;
