-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.users_id_seq...';END$$;
CREATE SEQUENCE public.users_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.users_id_seq OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.users...';END$$;
CREATE TABLE public.users (
    id integer NOT NULL DEFAULT nextval('public.users_id_seq'::regclass),
    username character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.users OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.users_id_seq...';END$$;
ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;

SET check_function_bodies = true;
