-- Script generated by Redgate Compare v1.23.0.23969
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.bill_id_seq...';END$$;
CREATE SEQUENCE public.bill_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.bill_id_seq OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.bill...';END$$;
CREATE TABLE public.bill (
    id integer NOT NULL DEFAULT nextval('public.bill_id_seq'::regclass),
    amount numeric(10,2) NOT NULL,
    due_date date NOT NULL,
    paid boolean DEFAULT false
);
ALTER TABLE public.bill ADD CONSTRAINT bill_pkey PRIMARY KEY (id);
ALTER TABLE public.bill OWNER TO postgres;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.bill_id_seq...';END$$;
ALTER SEQUENCE public.bill_id_seq OWNED BY public.bill.id;

SET check_function_bodies = true;
